version: "3.8"

name: frappe-crm

services:
  mariadb:
    image: mariadb:10.8
    container_name: frappe_mariadb
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: frappe_redis
    restart: unless-stopped

  frappe:
    image: frappe/bench:latest
    container_name: frappe_app
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    #command: bash /workspace/init.sh
    command: sleep infinity
    working_dir: /home/frappe
    environment:
      SHELL: /bin/bash
    volumes:
      - .:/workspace
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/frappe-bench/logs
    expose:
      - "8000"
      - "9000"

volumes:
  mariadb-data:
  frappe-sites:
  frappe-logs:
